### ISSUE TITLE
"TypeError: 'NoneType' object cannot be interpreted as an integer" when rendering a graph

### ISSUE THREAD

**Issue by nanocryk** [ConsenSys/mythril-classic#1018]
## Description

Can't produce a graph when following wiki commands

## How to Reproduce

Following this wiki page :
https://github.com/ConsenSys/mythril-classic/wiki/Control-Flow-Graph

Option `-i` don't exist.
If I remove it, i get :

```
$ python -m mythril -g graph.html -a 0x5c436ff914c458983414019195e0f4ecbef9e6dd
mythril.interfaces.cli [ERROR]: Traceback (most recent call last):
  File "/home/jeremyp/.local/lib/python3.7/site-packages/mythril/interfaces/cli.py", line 527, in parse_args
    disassembler=dissasembler, address=address, parser=parser, args=args
  File "/home/jeremyp/.local/lib/python3.7/site-packages/mythril/interfaces/cli.py", line 435, in execute_command
    phrackify=args.phrack,
  File "/home/jeremyp/.local/lib/python3.7/site-packages/mythril/mythril/mythril_analyzer.py", line 110, in graph_html
    enable_iprof=self.enable_iprof,
  File "/home/jeremyp/.local/lib/python3.7/site-packages/mythril/analysis/symbolic.py", line 114, in __init__
    self.laser.sym_exec(address)
  File "/home/jeremyp/.local/lib/python3.7/site-packages/mythril/laser/ethereum/svm.py", line 135, in sym_exec
    self._execute_transactions(main_address)
  File "/home/jeremyp/.local/lib/python3.7/site-packages/mythril/laser/ethereum/svm.py", line 176, in _execute_transactions
    for i in range(self.transaction_count):
TypeError: 'NoneType' object cannot be interpreted as an integer
```

I get the same error when running it with Docker :
```
$ docker run -v $(pwd):/tmp mythril/myth -g /tmp/graph.html -a 0x5c436ff914c458983414019195e0f4ecbef9e6dd --max-depth 8
mythril.interfaces.cli [ERROR]: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.4-py3.6.egg/mythril/interfaces/cli.py", line 527, in parse_args
    disassembler=dissasembler, address=address, parser=parser, args=args
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.4-py3.6.egg/mythril/interfaces/cli.py", line 435, in execute_command
    phrackify=args.phrack,
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.4-py3.6.egg/mythril/mythril/mythril_analyzer.py", line 110, in graph_html
    enable_iprof=self.enable_iprof,
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.4-py3.6.egg/mythril/analysis/symbolic.py", line 114, in __init__
    self.laser.sym_exec(address)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.4-py3.6.egg/mythril/laser/ethereum/svm.py", line 135, in sym_exec
    self._execute_transactions(main_address)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.4-py3.6.egg/mythril/laser/ethereum/svm.py", line 176, in _execute_transactions
    for i in range(self.transaction_count):
TypeError: 'NoneType' object cannot be interpreted as an integer
```

## Expected behavior

A working graph generation.

## Environment

- Mythril version: 0.20.4
- Solidity compiler and version: None
- Python version: 3.7.3
- OS and Version: Linux Manjaro

**Comment by norhh** [comment]
Hey @nanocryk , this has been fixed in the develop, can you try it with the develop branch of mythril.

**Comment by nanocryk** [comment]
Thank you for your quick response.

I'm not very familiar with Python, how do I run it from source ?

**Comment by nanocryk** [comment]
Thanks for your quick response.
I cloned the repo on `develop` branch then run :

```
$ ./myth -g graph.html -a 0x5c436ff914c458983414019195e0f4ecbef9e6dd
```

And it just wait. Am I supposed to connect to some ip:port ?

**Comment by norhh** [comment]
It's not needed if you are trying on a contract in mainnet, otherwise you might need to connect to your local host port.

**Comment by nanocryk** [comment]
I trying with `--rpc infura-mainnet`, but it keeps waiting without creating a `graph.html` file.

**Comment by norhh** [comment]
It takes some time, try it with `--transaction-count 1` flag, that may speed it up to a bit, also you can try reducing the max-depth to `--max-depth 15` or something like that

**Comment by nanocryk** [comment]
OK, it was just taking a very long amount of time. Maybe add some spinner or progress bar ?

I don't know if I should open another issue for this, but now that the graph is generated, it have some rendering problems
![image](https://user-images.githubusercontent.com/6422796/57085891-66e01d00-6cfd-11e9-9880-b497b659e9a2.png)

I'm using Firefox 66.0.3 (64-bit).

**Comment by norhh** [comment]
Probably opening another issue might help.

**Comment by norhh** [comment]
This maybe due to a large amount of states, can you try it with lesser depth
