### ISSUE TITLE
exception error when using 4.7.1 version of Z3

### ISSUE THREAD

**Issue by SunBeomSo** [ConsenSys/mythril-classic#1020]
## Description
Using the version 4.7.1 of Z3, I encountered an error message. 
Is the use of 4.7.1 version of Z3 not possible for running the latest version of Mythril?

## How to Reproduce
I simply typed:
```
./myth -x test.sol
```

## Screenshots

```
 Exception occurred, aborting analysis. Please report this issue to the Mythril GitHub page.
Traceback (most recent call last):
  File "/home/sunbeom/mythril-classic/mythril/mythril/mythril_analyzer.py", line 147, in fire_lasers
    enable_iprof=self.enable_iprof,
  File "/home/sunbeom/mythril-classic/mythril/analysis/symbolic.py", line 107, in __init__
    creation_code=contract.creation_code, contract_name=contract.name
  File "/home/sunbeom/mythril-classic/mythril/laser/ethereum/svm.py", line 140, in sym_exec
    self, creation_code, contract_name
  File "/home/sunbeom/mythril-classic/mythril/laser/ethereum/transaction/symbolic.py", line 102, in execute_contract_creation
    laser_evm.exec(True)
  File "/home/sunbeom/mythril-classic/mythril/laser/ethereum/svm.py", line 217, in exec
    new_states, op_code = self.execute_state(global_state)
  File "/home/sunbeom/mythril-classic/mythril/laser/ethereum/svm.py", line 266, in execute_state
    self._execute_pre_hook(op_code, global_state)
  File "/home/sunbeom/mythril-classic/mythril/laser/ethereum/svm.py", line 529, in _execute_pre_hook
    hook(global_state)
  File "/home/sunbeom/mythril-classic/mythril/analysis/modules/integer.py", line 110, in execute
    func(state)
  File "/home/sunbeom/mythril-classic/mythril/analysis/modules/integer.py", line 177, in _handle_exp
    model = self._try_constraints(state.mstate.constraints, [constraint])
  File "/home/sunbeom/mythril-classic/mythril/analysis/modules/integer.py", line 333, in _try_constraints
    return solver.get_model(constraints + new_constraints)
  File "/home/sunbeom/mythril-classic/mythril/analysis/solver.py", line 39, in get_model
    s.add(constraint)
  File "/home/sunbeom/mythril-classic/mythril/laser/smt/solver/solver.py", line 37, in add
    self.raw.add(z3_constraints)
  File "/usr/lib/python3/dist-packages/z3/z3.py", line 7012, in add
    self.assert_exprs(*args)
  File "/usr/lib/python3/dist-packages/z3/z3.py", line 7008, in assert_exprs
    Z3_optimize_assert(self.ctx.ref(), self.optimize, arg.as_ast())
AttributeError: 'bool' object has no attribute 'as_ast'
```

## Environment

- Mythril version: output from  0.20.4
- Solidity compiler and version: 0.4.25
- Python version: Python 3.6.7
- OS and Version: Ubuntu 18.04.2

**Comment by norhh** [comment]
Hi @SunBeomSo, currently Mythril doesn't work well with older z3 versions, due to some bugs or other issues, so we are using a recent version of it https://pypi.org/project/z3-solver-mythril/

**Comment by SunBeomSo** [comment]
Thanks for your answer. I close the issue.
