### ISSUE TITLE
Mythril raises a KeyError for a contract

### ISSUE THREAD

**Issue by norhh** [ConsenSys/mythril-classic#651]
## Description
Mythril raises a KeyError when run with contract `0x8601e58163C2713B06b40a2000A30FF4A988e926`

## How to Reproduce
```console
$ myth -xila 0x8601e58163C2713B06b40a2000A30FF4A988e926
Traceback (most recent call last):
  File "./myth", line 9, in <module>
    mythril.interfaces.cli.main()
  File "/home/nikhil/MYTHRIL/mythril/mythril/interfaces/cli.py", line 397, in main
    max_transaction_count=args.max_transaction_count,
  File "/home/nikhil/MYTHRIL/mythril/mythril/mythril.py", line 470, in fire_lasers
    issues = fire_lasers(sym, modules)
  File "/home/nikhil/MYTHRIL/mythril/mythril/analysis/security.py", line 20, in fire_lasers
    issues += module.execute(statespace)
  File "/home/nikhil/MYTHRIL/mythril/mythril/analysis/modules/exceptions.py", line 44, in execute
    solver.get_transaction_sequence(state, node.constraints)
  File "/home/nikhil/MYTHRIL/mythril/mythril/analysis/solver.py", line 109, in get_transaction_sequence
    txs[tx_id]["caller"] = caller
KeyError: 'storage_KECCAC[1]'

...
$
```

## Expected behavior
Contract should be executed without any errors

## Environment

- Mythril version: develop
- Solidity compiler and version: `0.4.25`
- Python version: `3.6`
- OS and Version: Ubuntu 17.10

**Comment by nbanmp** [comment]
I'll take care of this.
