### ISSUE TITLE
Crashes due to corrupted signatures.json

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril-classic#720]
## Description

Under "stressful" conditions (executing `myth` multiple times, aborting with CTRL+c,...) Mythril encounters exceptions such as `JSONDecodeError`  errors and `ValueError` as the signature file breaks. 

E.g.

```
$ myth -mether_thief -x tokensale.sol --verbose-report
ERROR:root:Solc experienced a fatal error (code 1).

""tokensale.sol"" is not found

(mythril) cerebral-cortex:Medium_Posts bernhardmueller$ myth -mether_thief -x tokensalechallenge.sol --verbose-report
Traceback (most recent call last):
  File "/Users/bernhardmueller/.pyenv/versions/mythril/bin/myth", line 11, in <module>
    load_entry_point('mythril==0.19.6', 'console_scripts', 'myth')()
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/envs/mythril/lib/python3.6/site-packages/mythril/interfaces/cli.py", line 348, in main
    address, _ = mythril.load_from_solidity(args.solidity_file)  # list of files
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/envs/mythril/lib/python3.6/site-packages/mythril/mythril.py", line 406, in load_from_solidity
    solc_binary=self.solc_binary,
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/envs/mythril/lib/python3.6/site-packages/mythril/ether/soliditycontract.py", line 39, in get_contracts_from_file
    solc_binary=solc_binary,
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/envs/mythril/lib/python3.6/site-packages/mythril/ether/soliditycontract.py", line 101, in __init__
    super().__init__(code, creation_code, name=name)
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/envs/mythril/lib/python3.6/site-packages/mythril/ether/ethcontract.py", line 22, in __init__
    self.disassembly = Disassembly(code, enable_online_lookup=enable_online_lookup)
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/envs/mythril/lib/python3.6/site-packages/mythril/disassembler/disassembly.py", line 30, in __init__
    signatures.open()  # open from default locations
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/envs/mythril/lib/python3.6/site-packages/mythril/support/signatures.py", line 100, in open
    sigs = json.load(f)
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/lib/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 245 (char 244)
```

Contents of signatures file:

```
 cat ~/.mythril/signatures.json
{"0x2eb00c1b": ["pwnContract()"], "0x41c0e1b5": ["kill()"], "0x70a08231": ["balanceOf(address)"], "0xa6e0e35e": ["activateBackdoor(bytes11)"], "0xb2fa1c9e": ["isComplete()"], "0xd96a094a": ["buy(uint256)"], "0xe4849b32": ["sell(uint256)"]}     "isComplete()"
    ],
    "0xd96a094a": [
        "buy(uint256)"
    ],
    "0xe4849b32": [
        "sell(uint256)"
    ]
```

## How to Reproduce

Running mythril against the same file multiple times will usually result in an error.

## Environment

- Mythril version: develop
- Solidity compiler and version: 0.4.24+commit.e67f0147.Darwin.appleclang
- Python version: 3.6.4
- OS and Version: Mac OS Mojave

**Comment by b-mueller** [comment]
Second error after running Mythril twice on [tokensale.sol](https://capturetheether.com/challenges/math/token-sale/):

```
$ myth -x -minteger --verbose-report tokensale.sol 
Traceback (most recent call last):
  File "/Users/bernhardmueller/.pyenv/versions/mythril/bin/myth", line 11, in <module>
    load_entry_point('mythril==0.19.7', 'console_scripts', 'myth')()
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/envs/mythril/lib/python3.6/site-packages/mythril/interfaces/cli.py", line 282, in main
    enable_online_lookup=args.query_signature,
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/envs/mythril/lib/python3.6/site-packages/mythril/mythril.py", line 101, in __init__
    enable_online_lookup=self.enable_online_lookup
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/envs/mythril/lib/python3.6/site-packages/mythril/support/signatures.py", line 61, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/envs/mythril/lib/python3.6/site-packages/mythril/support/signatures.py", line 80, in __init__
    self.open()
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/envs/mythril/lib/python3.6/site-packages/mythril/support/signatures.py", line 130, in open
    path, sighash, funcsig
ValueError: Malformed signature file at /Users/bernhardmueller/.mythril/signatures.json. 0x3432fcbb: TokenSaleChallenge(address) is not a valid entry
```

**Comment by dmuhs** [comment]
Dealing with the JSON file has been quite a pain, especially maintaining consistency for concurrent access. Over the weekend I hacked up a smaller signature DB that uses SQLite. I'm currently brushing it up a little and see how I can integrate it with the points where the old DB is currently used. :+1:

**Comment by b-mueller** [comment]
Yeah, the JSON file has always been a major pain 😢

**Comment by dmuhs** [comment]
#758 merged, major pain removed. Dr. Muhs signing off. :+1:
