### ISSUE TITLE
KeyError in get_transaction_sequence

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril-classic#738]
## Description

Mythril crashes with a `KeyError` exception when analyzing an instance of Parity WalletLibrary.

## How to Reproduce

```
$ myth --rpc infura-ropsten -xa 0xf5527f393a77123912db9e62466c3413c4acc64e
Traceback (most recent call last):
  File "/Users/bernhardmueller/.pyenv/versions/3.5.2/bin/myth", line 9, in <module>
    load_entry_point('mythril==0.19.0', 'console_scripts', 'myth')()
  File "/Users/bernhardmueller/.pyenv/versions/3.5.2/lib/python3.5/site-packages/mythril-0.19.0-py3.5.egg/mythril/interfaces/cli.py", line 397, in main
    max_transaction_count=args.max_transaction_count,
  File "/Users/bernhardmueller/.pyenv/versions/3.5.2/lib/python3.5/site-packages/mythril-0.19.0-py3.5.egg/mythril/mythril.py", line 470, in fire_lasers
    issues = fire_lasers(sym, modules)
  File "/Users/bernhardmueller/.pyenv/versions/3.5.2/lib/python3.5/site-packages/mythril-0.19.0-py3.5.egg/mythril/analysis/security.py", line 20, in fire_lasers
    issues += module.execute(statespace)
  File "/Users/bernhardmueller/.pyenv/versions/3.5.2/lib/python3.5/site-packages/mythril-0.19.0-py3.5.egg/mythril/analysis/modules/exceptions.py", line 44, in execute
    solver.get_transaction_sequence(state, node.constraints)
  File "/Users/bernhardmueller/.pyenv/versions/3.5.2/lib/python3.5/site-packages/mythril-0.19.0-py3.5.egg/mythril/analysis/solver.py", line 110, in get_transaction_sequence
    txs[tx_id]["caller"] = caller
KeyError: '1_(2)**(storage_KECCAC[1461501637330902918203684832716283019655932542975_&_1])'
```

## Environment

- Mythril version: v0.19.7
- Solidity compiler and version: 0.4.24+commit.e67f0147.Darwin.appleclang
- Python version: 3.6.4
- OS and Version: Mac OS Mojave

**Comment by norhh** [comment]
I think this was fixed by nathan in #651 (so the fix affects all versions > 0.19.5) , looking at your stacktrace it seems it was run with the version `0.19.0`, In that case can you recheck it with the latest `0.19.8` . It's taking forever running in my PC.

**Comment by norhh** [comment]
It seems to be fixed when I ran it in my PC(It took 20hrs), It can be closed right? @b-mueller

**Comment by b-mueller** [comment]
> It took 20hrs

Hehe.

Yep, looks good.
