### ISSUE TITLE
Docker fails to run, produces stack trace

### ISSUE THREAD

**Issue by mickayz** [ConsenSys/mythril-classic#823]
## Description

The current build on docker fails to run and produces a stack trace

## How to Reproduce

Run the following with any target solidity file

```
docker run --rm -v $(pwd):/tmp mythril/myth -x /tmp/target.sol
```

Observe the stack trace:

```
Traceback (most recent call last):
  File "/usr/local/bin/myth", line 11, in <module>
    load_entry_point('mythril==0.19.10', 'console_scripts', 'myth')()
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.19.10-py3.6.egg/mythril/interfaces/cli.py", line 293, in main
    enable_online_lookup=args.query_signature,
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.19.10-py3.6.egg/mythril/mythril.py", line 97, in __init__
    self.mythril_dir = self._init_mythril_dir()
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.19.10-py3.6.egg/mythril/mythril.py", line 130, in _init_mythril_dir
    copyfile(str(parent_dir / "signatures.db"), db_path)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/dist-packages/mythril-0.19.10-py3.6.egg/signatures.db'
```

The following target.sol was used in this example:

https://gist.github.com/mickayz/4d58ed15edc60d301a4f60fe193e1212

## Expected behavior

No crash

## Environment

Latest Docker image running 0.19.10

**Comment by norhh** [comment]
Making it high priority because it makes the release non usable.

**Comment by norhh** [comment]
Now it's working in docker but not in pypi :cry: .
