### ISSUE TITLE
Cannot execute myth -x command on Mojave 10.14 / Python 3.7.2

### ISSUE THREAD

**Issue by jklepatch** [ConsenSys/mythril-classic#864]
## Description

I installed  Mythrill:

```
brew update
brew upgrade
brew tap ethereum/ethereum
brew install leveldb
brew install solidity
pip3 install mythril
```

Then tried to run the mythrill command-line:

```
myth -x my_smart_contract.sol
```

But got this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/myth", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/mythril/interfaces/cli.py", line 293, in main
    enable_online_lookup=args.query_signature,
  File "/usr/local/lib/python3.7/site-packages/mythril/mythril.py", line 97, in __init__
    self.mythril_dir = self._init_mythril_dir()
  File "/usr/local/lib/python3.7/site-packages/mythril/mythril.py", line 130, in _init_mythril_dir
    copyfile(str(parent_dir / "signatures.db"), db_path)
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/site-packages/mythril/signatures.db'
```

I already tried this fix, without success (same error message):

```
mkdir ~/.mythrill
pip install --upgrade git+https://github.com/tintinweb/ethereum-dasm.git@master
```

## How to Reproduce

(See above)

## Expected behavior

Mythrill command-line should run properly

## Environment
- Mythril version: Mythril version v0.19.11
- Solidity compiler and version: Version: 0.5.2+commit.1df8f40c.Darwin.appleclang
- Python version: Python 2.7.15 (But python3 points to Python 3.7.2)
- OS and Version: Mojave 10.14

**Comment by norhh** [comment]
The fix version will be released soon. By then can you take the signatures.db file in mythril repo(https://github.com/ConsenSys/mythril-classic/blob/develop/signatures.db) and move it to `~/.mythril` directory. That might fix it.

**Comment by sbrichards** [comment]
I had this same issue. @norhh, your suggestion fixed it for me - thanks!

**Comment by norhh** [comment]
@sbrichards yes
