### ISSUE TITLE
TypeError in Docker

### ISSUE THREAD

**Issue by tlxnithin** [ConsenSys/mythril-classic#873]
## Description

Getting TypeError when trying to scan a truffle project with mythril docker image.

## How to Reproduce

```console
$ docker run -v <path-to-contract-folder>:/tmp -w "/tmp" mythril/myth --truffle
 
```

## Traceback
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.19.11-py3.6.egg/mythril/laser/ethereum/instructions.py", line 996, in sstore_
    index = util.get_concrete_int(index)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.19.11-py3.6.egg/mythril/laser/ethereum/util.py", line 76, in get_concrete_int
    raise TypeError("Got a symbolic BitVecRef")
TypeError: Got a symbolic BitVecRef

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/myth", line 11, in <module>
    load_entry_point('mythril==0.19.11', 'console_scripts', 'myth')()
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.19.11-py3.6.egg/mythril/interfaces/cli.py", line 328, in main
    mythril.analyze_truffle_project(args)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.19.11-py3.6.egg/mythril/mythril.py", line 210, in analyze_truffle_project
    self.sigs, *args, **kwargs
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.19.11-py3.6.egg/mythril/support/truffle.py", line 58, in analyze_truffle_project
    transaction_count=args.transaction_count,
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.19.11-py3.6.egg/mythril/analysis/symbolic.py", line 76, in __init__
    self.laser.sym_exec(address)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.19.11-py3.6.egg/mythril/laser/ethereum/svm.py", line 106, in sym_exec
    self._execute_transactions(main_address)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.19.11-py3.6.egg/mythril/laser/ethereum/svm.py", line 154, in _execute_transactions
    execute_message_call(self, address)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.19.11-py3.6.egg/mythril/laser/ethereum/transaction/symbolic.py", line 57, in execute_message_call
    laser_evm.exec()
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.19.11-py3.6.egg/mythril/laser/ethereum/svm.py", line 186, in exec
    new_states, op_code = self.execute_state(global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.19.11-py3.6.egg/mythril/laser/ethereum/svm.py", line 213, in execute_state
    global_state
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.19.11-py3.6.egg/mythril/laser/ethereum/instructions.py", line 153, in evaluate
    return instruction_mutator(global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.19.11-py3.6.egg/mythril/laser/ethereum/instructions.py", line 112, in wrapper
    new_global_states = self.call_on_state_copy(func, func_obj, global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.19.11-py3.6.egg/mythril/laser/ethereum/instructions.py", line 77, in call_on_state_copy
    return func(func_obj, global_state_copy)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.19.11-py3.6.egg/mythril/laser/ethereum/instructions.py", line 1033, in sstore_
    new = Or(new, key_argument != index_argument)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.19.11-py3.6.egg/mythril/laser/smt/bool.py", line 56, in Or
    union = a.annotations + b.annotations
AttributeError: 'bool' object has no attribute 'annotations'
```

## Environment

Docker Mythril version: 0.19.11

**Comment by norhh** [comment]
hey @tlxnithin , can you use our docker-dev container? It has that bug fixed, use `docker pull mythril/myth-dev`

**Comment by tlxnithin** [comment]
@norhh Thanks for responding. I tried that as well. I took the dev branch and built docker image myself. Also I pulled the dev image you suggested, am getting the error as below for both.

```
Traceback (most recent call last):
  File "/usr/local/bin/myth", line 11, in <module>
    load_entry_point('mythril==0.19.11', 'console_scripts', 'myth')()
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.19.11-py3.6.egg/mythril/interfaces/cli.py", line 301, in main
    enable_online_lookup=args.query_signature,
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.19.11-py3.6.egg/mythril/mythril.py", line 105, in __init__
    self.mythril_dir = self._init_mythril_dir()
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.19.11-py3.6.egg/mythril/mythril.py", line 138, in _init_mythril_dir
    copyfile(str(parent_dir / "signatures.db"), db_path)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/dist-packages/mythril-0.19.11-py3.6.egg/signatures.db'

```

**Comment by tlxnithin** [comment]
I saw signatures.db in the repo and added a line in Dockerfile to copy manually this file in the required path and everything went well. But do you know why such a difference in develop branch and v0.19.11?

**Comment by norhh** [comment]
@tlxnithin , yes there seems to be a bug in the develop branch for docker regarding that,
`Also I am getting "Integer Overflow" warning for string variable, why is it so?`might be a false positive,by anychance can you provide us a subset of that code which might result in that issue?

**Comment by tlxnithin** [comment]
Looks like "Integer Overflow" is showing a lot false positives. Here is the kind of code I am getting it against.

```
pragma solidity ^0.4.24;

contract Constants {

    string public ERROR_VALUE_EQUALS_ZERO = "ZERO VALUE";
    string public ERROR_DISALLOWED = "THIS FUNCTION IS DISALLOWED";

}
```

**Comment by norhh** [comment]
unfortunately i can't reproduce the error with that contract, can you mention if any other contract were also present in your truffle directory?

**Comment by tlxnithin** [comment]
Here is the truffle directory I am running it against, [https://github.com/tallyxinc/top-claims-book](https://github.com/tallyxinc/top-claims-book). Are you using the docker version?

**Comment by elenadimitrova** [comment]
@norhh I have the same issue as above and trying out the dev container is even failing to start the `myth` run. 
Command I am using for reference is 
```
docker run -it -v "$PWD"/build:/build mythril/myth-dev myth --truffle
```
Result is:
```
Traceback (most recent call last):
  File "/usr/local/bin/myth", line 11, in <module>
    load_entry_point('mythril==0.19.11', 'console_scripts', 'myth')()
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.19.11-py3.6.egg/mythril/interfaces/cli.py", line 301, in main
    enable_online_lookup=args.query_signature,
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.19.11-py3.6.egg/mythril/mythril.py", line 105, in __init__
    self.mythril_dir = self._init_mythril_dir()
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.19.11-py3.6.egg/mythril/mythril.py", line 138, in _init_mythril_dir
    copyfile(str(parent_dir / "signatures.db"), db_path)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/dist-packages/mythril-0.19.11-py3.6.egg/signatures.db'
```

**Comment by norhh** [comment]
Hey @tlxnithin , can you raise a separate issue for the false positives, I might need more data in terms of which truffle version, and what was the exact command that was run, so filling up the bug report template might be helpful for us. I am closing this issue as it was fixed in docker-dev container by https://github.com/ConsenSys/mythril-classic/pull/888 PR.

**Comment by tlxnithin** [comment]
> s it was fixed in docker-dev containe

Sure @norhh . Sorry, I forgot to close this.
