### ISSUE TITLE
Generation of statespace JSON file fails with `TypeError: unhashable type: 'BitVec'`

### ISSUE THREAD

**Issue by Ooqu4** [ConsenSys/mythril-classic#892]
## Description
Generation of statespace JSON file fails with `TypeError: unhashable type: 'BitVec'`

## How to Reproduce
The smart contract file `storage_set_get` can be found [here](https://gist.github.com/Ooqu4/8a622716a4ac73d8cdd981462ec940fd).

```bash
$ myth --statespace-json statespace.json storage_set_get.sol --max-depth 1
Traceback (most recent call last):
  File "/home/user/.local/bin/myth", line 11, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.6/site-packages/mythril/interfaces/cli.py", line 448, in main
    create_timeout=args.create_timeout,
  File "/home/user/.local/lib/python3.6/site-packages/mythril/mythril.py", line 441, in dump_statespace
    return get_serializable_statespace(sym)
  File "/home/user/.local/lib/python3.6/site-packages/mythril/analysis/traceexplore.py", line 96, in get_serializable_statespace
    for x in node.states
  File "/home/user/.local/lib/python3.6/site-packages/mythril/analysis/traceexplore.py", line 96, in <listcomp>
    for x in node.states
  File "/home/user/.local/lib/python3.6/site-packages/mythril/analysis/traceexplore.py", line 89, in get_state_accounts
    storage[str(storage_key)] = str(account["storage"][storage_key])
  File "/home/user/.local/lib/python3.6/site-packages/mythril/laser/ethereum/state/account.py", line 26, in __getitem__
    return self._storage[item]
TypeError: unhashable type: 'BitVec'
```

It looks like the storage object was once a simple Python dict, but is now
packed into its own storage object.

## Expected behavior

Generation of `statespace.json` file w/o errors.

# Fix suggestion

Replace
https://github.com/ConsenSys/mythril-classic/blob/4c4e0ee0bd5a6da7e8680e1f36fa92eb1b56228d/mythril/analysis/traceexplore.py#L100-L101

with

```python
for storage_key, storage_value in account["storage"]._storage.items():
    storage[str(storage_key)] = str(storage_value)
```

This fix is not optimal since the private variable `_storage` is accessed from
outside the object.
I'm sure there is a better solution.

__Note__: I was not able to verify the correctness of the fix  because the computation
exceeded my 6GB of RAM and aborted. Not sure if such a resource consumption can be
expected or if there is an other problem.

## Environment

- Mythril version: v0.19.11
- Solidity compiler and version: 0.5.0+commit.1d4f565a.Linux.g++
- Python version: 3.6.7
- OS and Version: Ubuntu 18.04.1 LTS (64-bit)

**Comment by norhh** [comment]
Hi @Ooqu4 , thanks for the report. there were two bugs actually :sweat_smile: . One was the unhashable BitVec one, and the second would be the memory overflow for a very small depths which you mentioned. this commit should fix it https://github.com/ConsenSys/mythril-classic/pull/893/commits/1a0e65f4e43d2a5090c961f3e5fef6432cfaed4a .
