### ISSUE TITLE
mythril.mythril CRITICAL Exception in mythril.py

### ISSUE THREAD

**Issue by askyst** [ConsenSys/mythril-classic#939]
## Description
The security analysis option (-x) doest not work. The output of the myth told me to report this issue. So here it is. 

## How to Reproduce
Install myth using docker: docker pull mythril/myth

Run it: 
$ docker run -v `pwd`:/work  mythril/myth   --solv 0.4.25  -x   /work/UpgradeabilityProxyFactory_all.sol
Error part of output :
2019-02-26 08:09:17 (754 KB/s) - ‘/root/.py-solc/solc-v0.4.25/bin/solc’ saved [4973312/4973312]

mythril.mythril [CRITICAL]: Exception occurred, aborting analysis. Please report this issue to the Mythril GitHub page.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/mythril.py", line 586, in fire_lasers
    enable_iprof=enable_iprof,
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/analysis/symbolic.py", line 102, in __init__
    creation_code=contract.creation_code, contract_name=contract.name
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/svm.py", line 132, in sym_exec
    self, creation_code, contract_name
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/transaction/symbolic.py", line 102, in execute_contract_creation
    laser_evm.exec(True)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/svm.py", line 232, in exec
    new_states, op_code = self.execute_state(global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/svm.py", line 276, in execute_state
    ).evaluate(global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/instructions.py", line 198, in evaluate
    result = instruction_mutator(global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/instructions.py", line 145, in wrapper
    new_global_states = self.call_on_state_copy(func, func_obj, global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/instructions.py", line 89, in call_on_state_copy
    return func(func_obj, global_state_copy)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/instructions.py", line 1207, in mstore_
    state.memory.write_word_at(mstart, value)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/state/memory.py", line 82, in write_word_at
    self[index : index + 32] = _bytes
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/state/memory.py", line 135, in __setitem__
    self[start + i] = value[i]
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/state/memory.py", line 142, in __setitem__
    self._memory[key] = value
IndexError: cannot fit 'int' into an index-sized integer
 
mythril.mythril [CRITICAL]: Exception occurred, aborting analysis. Please report this issue to the Mythril GitHub page.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/mythril.py", line 586, in fire_lasers
    enable_iprof=enable_iprof,
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/analysis/symbolic.py", line 102, in __init__
    creation_code=contract.creation_code, contract_name=contract.name
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/svm.py", line 132, in sym_exec
    self, creation_code, contract_name
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/transaction/symbolic.py", line 102, in execute_contract_creation
    laser_evm.exec(True)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/svm.py", line 232, in exec
    new_states, op_code = self.execute_state(global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/svm.py", line 276, in execute_state
    ).evaluate(global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/instructions.py", line 198, in evaluate
    result = instruction_mutator(global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/instructions.py", line 145, in wrapper
    new_global_states = self.call_on_state_copy(func, func_obj, global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/instructions.py", line 89, in call_on_state_copy
    return func(func_obj, global_state_copy)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/instructions.py", line 1207, in mstore_
    state.memory.write_word_at(mstart, value)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/state/memory.py", line 82, in write_word_at
    self[index : index + 32] = _bytes
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/state/memory.py", line 135, in __setitem__
    self[start + i] = value[i]
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/state/memory.py", line 142, in __setitem__
    self._memory[key] = value
IndexError: cannot fit 'int' into an index-sized integer
 
Downloading static linux binary from https://github.com/ethereum/solidity/releases/download/v0.4.25/solc-static-linux
Executing: wget https://github.com/ethereum/solidity/releases/download/v0.4.25/solc-static-linux -c -O /root/.py-solc/solc-v0.4.25/bin/solc
Checking installed executable version @ /root/.py-solc/solc-v0.4.25/bin/solc
Executing: /root/.py-solc/solc-v0.4.25/bin/solc --version
solc successfully installed at: /root/.py-solc/solc-v0.4.25/bin/solc
The analysis was completed successfully. No issues were detected.

## Environment

Please modify for your setup

- OS and Version: Debian Linux 9.8.

**Comment by JoranHonig** [comment]
Thanks for the report! You'll probably hear from us later once we have a fix in the works. 
In the meanwhile, are you able to share the contract that mythril reports this issue for?

**Comment by askyst** [comment]
Sorry, at the moment the contract is not for public use (it is used in a private chain.) so I cannot share it here...

**Comment by norhh** [comment]
@askyst , can you mention your system's ram on which this was executed?

**Comment by askyst** [comment]
The system has 16G memory.

**Comment by askyst** [comment]
Speaking of memory, when I test another contract in the project, it did produce another error which is called " MemoryError".

mythril.mythril [CRITICAL]: Exception occurred, aborting analysis. Please report this issue to the Mythril GitHub page.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/mythril.py", line 586, in fire_lasers
    enable_iprof=enable_iprof,
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/analysis/symbolic.py", line 102, in __init__
    creation_code=contract.creation_code, contract_name=contract.name
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/svm.py", line 145, in sym_exec
    self._execute_transactions(created_account.address)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/svm.py", line 184, in _execute_transactions
    execute_message_call(self, address)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/transaction/symbolic.py", line 58, in execute_message_call
    laser_evm.exec()
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/svm.py", line 232, in exec
    new_states, op_code = self.execute_state(global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/svm.py", line 276, in execute_state
    ).evaluate(global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/instructions.py", line 198, in evaluate
    result = instruction_mutator(global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/instructions.py", line 145, in wrapper
    new_global_states = self.call_on_state_copy(func, func_obj, global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/instructions.py", line 89, in call_on_state_copy
    return func(func_obj, global_state_copy)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/instructions.py", line 384, in add_
    + helper.pop_bitvec(global_state.mstate)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/smt/bitvec.py", line 61, in __add__
    union = self.annotations + other.annotations
MemoryError

**Comment by askyst** [comment]
I managed to write a smaller contract which will reproduce the "
IndexError: cannot fit 'int' into an index-sized integer" error.  Hope it will help :)
The problem seems related to the library usage...

pragma solidity ^0.4.24;
library la {
  function aa(address a) internal view returns (bool) {
    uint256 size;
    assembly { size := extcodesize(a) }
    return size>0;
  }
}
contract a 
{
  constructor(address bb) public {
    c(bb);  //_setImplementation
  }
  function c(address bb) private { //_setImplementation
    require(la.aa(bb), "error");
  }
}

**Comment by norhh** [comment]
@askyst , awesome, thanks a lot. we are currently trying to support library usage error, will try to fix it soon.
