### ISSUE TITLE
Mythril crashes when compiling Solidity code

### ISSUE THREAD

**Issue by b-mueller** [ConsenSys/mythril-classic#959]
## Description

Mythril crashes when analyzing BECToken.sol:

```
$ myth -x BECToken.sol 
mythril.interfaces.cli [ERROR]: Traceback (most recent call last):
  File "/Users/bernhardmueller/PycharmProjects/mythril-classic/mythril/interfaces/cli.py", line 530, in parse_args
    address = get_code(mythril, args)
  File "/Users/bernhardmueller/PycharmProjects/mythril-classic/mythril/interfaces/cli.py", line 380, in get_code
    address, _ = mythril.load_from_solidity(args.solidity_file)  # list of files
  File "/Users/bernhardmueller/PycharmProjects/mythril-classic/mythril/mythril.py", line 452, in load_from_solidity
    solc_binary=self.solc_binary,
  File "/Users/bernhardmueller/PycharmProjects/mythril-classic/mythril/solidity/soliditycontract.py", line 45, in get_contracts_from_file
    data = get_solc_json(input_file, solc_args=solc_args, solc_binary=solc_binary)
  File "/Users/bernhardmueller/PycharmProjects/mythril-classic/mythril/ethereum/util.py", line 70, in get_solc_json
    return json.loads(out)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
I reproduced this with solc 0.4.25, 0.5.0 and 0.5.6. I also verified that the contract successfully compiles with `solc --bin-runtime`.

## Expected behavior

Should parse the compiler output without errors.

## Environment
- Mythril version: develop
- Solidity compiler and version: All
- Python version: 3.6.3
- OS and Version: Mojave

**Comment by norhh** [comment]
That contract seems to work perfectly in my PC on python 3.6 and python3.7.2, can you try running it in a virtual environment?

**Comment by b-mueller** [comment]
I just installed into a fresh virtualenv and get the same output:

```
$ $MYTH -x BECToken.sol:BecToken
mythril.interfaces.cli [ERROR]: Traceback (most recent call last):
  File "/Users/bernhardmueller/PycharmProjects/mythril-classic/mythril/interfaces/cli.py", line 530, in parse_args
    address = get_code(mythril, args)
  File "/Users/bernhardmueller/PycharmProjects/mythril-classic/mythril/interfaces/cli.py", line 380, in get_code
    address, _ = mythril.load_from_solidity(args.solidity_file)  # list of files
  File "/Users/bernhardmueller/PycharmProjects/mythril-classic/mythril/mythril.py", line 444, in load_from_solidity
    solc_binary=self.solc_binary,
  File "/Users/bernhardmueller/PycharmProjects/mythril-classic/mythril/solidity/soliditycontract.py", line 65, in __init__
    data = get_solc_json(input_file, solc_args=solc_args, solc_binary=solc_binary)
  File "/Users/bernhardmueller/PycharmProjects/mythril-classic/mythril/ethereum/util.py", line 70, in get_solc_json
    return json.loads(out)
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/bernhardmueller/.pyenv/versions/3.6.3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Are you testing with the develop branch?

**Comment by norhh** [comment]
@b-mueller, Tried the same, still no errors :disappointed:, in that case does mythril/myth-dev image work for you?

**Comment by JoranHonig** [comment]
@norhh In any case I think mythril should fail gracefully in this case.

Basically mythril should output:
```
The output from solc seems to be malformed, decoding encountered the following error:
Expecting value: line 1 column 1 (char 0)

The solc output was:
...
```

This will make triaging this bug easier, and the user experience better

**Comment by b-mueller** [comment]
Ok, I found the issue. It was all my fault :/

I had installed Trailofbit's solc-select wrapper and apparently that isn't compatible with Mythril Classic. Using normal solc instead and it works again.
