### ISSUE TITLE
"Got a symbolic BitVecRef" + "MemoryError"

### ISSUE THREAD

**Issue by Gullintani** [ConsenSys/mythril-classic#970]
## Description
I wrote a script to scan a list of addresses, this error appears when scanning a smart contract of "Axie Infinity | 0x020f9e661e512132890d259dc363ed084cf4e5a6". The error asked to report this issue.

Thinkpad X270
Ubuntu 18.04
Latest docker
Latest Mythril

## Error Log
mythril.mythril [CRITICAL]: Exception occurred, aborting analysis. Please report this issue to the Mythril GitHub page.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/state/memory.py", line 48, in get_word_at
    bytes([util.get_concrete_int(b) for b in self[index : index + 32]]),
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/state/memory.py", line 48, in <listcomp>
    bytes([util.get_concrete_int(b) for b in self[index : index + 32]]),
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/util.py", line 111, in get_concrete_int
    raise TypeError("Got a symbolic BitVecRef")
TypeError: Got a symbolic BitVecRef

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/mythril.py", line 586, in fire_lasers
    enable_iprof=enable_iprof,
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/analysis/symbolic.py", line 109, in __init__
    self.laser.sym_exec(address)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/svm.py", line 127, in sym_exec
    self._execute_transactions(main_address)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/svm.py", line 184, in _execute_transactions
    execute_message_call(self, address)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/transaction/symbolic.py", line 58, in execute_message_call
    laser_evm.exec()
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/svm.py", line 232, in exec
    new_states, op_code = self.execute_state(global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/svm.py", line 276, in execute_state
    ).evaluate(global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/instructions.py", line 198, in evaluate
    result = instruction_mutator(global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/instructions.py", line 145, in wrapper
    new_global_states = self.call_on_state_copy(func, func_obj, global_state)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/instructions.py", line 89, in call_on_state_copy
    return func(func_obj, global_state_copy)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/instructions.py", line 1177, in mload_
    data = state.memory.get_word_at(offset)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/ethereum/state/memory.py", line 58, in get_word_at
    for b in self[index : index + 32]
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.20.0-py3.6.egg/mythril/laser/smt/bitvec.py", line 246, in Concat
    annotations += bv.annotations
MemoryError

Thank you for making this fabulous work!

**Comment by norhh** [comment]
Hi @Gullintani , thanks for reporting the issue, by the way the latest mythril version currently is `v0.20.2`, can you try using that?

**Comment by Gullintani** [comment]
Sorry I will have a try!

**Comment by Gullintani** [comment]
I'm sorry for my uncarefulness! It fixed in `v0.20.2`, thank you @norhh !
